name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: bokuweb/actions-test@b
        with:
          secret: "${{ secrets.GITHUB_TOKEN }}"
